---
- name: Install and start web server
  hosts: multipass_vms
  vars:
    package_name: "{{ 'nginx' if ansible_facts['os_family'] == 'Debian' else 'httpd' }}"
    service_name: "{{ 'nginx' if ansible_facts['os_family'] == 'Debian' else 'httpd' }}"
  tasks:
    - name: Install web server package
      package:
        name: "{{ package_name }}"
        state: present
    - name: Ensure web server service is running
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes

